import Head from "next/head";
import Sidebar from "../components/Sidebar";
import Chat from "./chat/[id]";

export default function Home() {
	return (
		<div>
			<Head>
				<title>Create Next App</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className="flex">
				<Sidebar />
				<Chat />
			</main>
		</div>
	);
}